package com.example.weibohuati.model;

public class UserTopicFollow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_follow.id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_follow.user_id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_follow.topic_id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    private Integer topic_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_follow.id
     *
     * @return the value of user_topic_follow.id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_follow.id
     *
     * @param id the value for user_topic_follow.id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_follow.user_id
     *
     * @return the value of user_topic_follow.user_id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_follow.user_id
     *
     * @param user_id the value for user_topic_follow.user_id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_follow.topic_id
     *
     * @return the value of user_topic_follow.topic_id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    public Integer getTopic_id() {
        return topic_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_follow.topic_id
     *
     * @param topic_id the value for user_topic_follow.topic_id
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    public void setTopic_id(Integer topic_id) {
        this.topic_id = topic_id;
    }
}