package com.example.weibohuati.model;

import java.io.Serializable;
import java.util.Date;

public class Weibo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibo.id
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibo.content
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibo.img_url
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    private String img_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibo.like_count
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    private Integer like_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibo.remark_count
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    private Integer remark_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibo.create_time
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibo.user_id
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    private Integer user_id;

    private Integer topic_id;

    public Integer getTopic_id() {
        return topic_id;
    }

    public void setTopic_id(Integer topic_id) {
        this.topic_id = topic_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibo.id
     *
     * @return the value of weibo.id
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibo.id
     *
     * @param id the value for weibo.id
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibo.content
     *
     * @return the value of weibo.content
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibo.content
     *
     * @param content the value for weibo.content
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibo.img_url
     *
     * @return the value of weibo.img_url
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public String getImg_url() {
        return img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibo.img_url
     *
     * @param img_url the value for weibo.img_url
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public void setImg_url(String img_url) {
        this.img_url = img_url == null ? null : img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibo.like_count
     *
     * @return the value of weibo.like_count
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public Integer getLike_count() {
        return like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibo.like_count
     *
     * @param like_count the value for weibo.like_count
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public void setLike_count(Integer like_count) {
        this.like_count = like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibo.remark_count
     *
     * @return the value of weibo.remark_count
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public Integer getRemark_count() {
        return remark_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibo.remark_count
     *
     * @param remark_count the value for weibo.remark_count
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public void setRemark_count(Integer remark_count) {
        this.remark_count = remark_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibo.create_time
     *
     * @return the value of weibo.create_time
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibo.create_time
     *
     * @param create_time the value for weibo.create_time
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibo.user_id
     *
     * @return the value of weibo.user_id
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibo.user_id
     *
     * @param user_id the value for weibo.user_id
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}