package com.example.weibohuati.mapper;

import com.example.weibohuati.model.UserWeiboLike;
import com.example.weibohuati.model.UserWeiboLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWeiboLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    long countByExample(UserWeiboLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    int deleteByExample(UserWeiboLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    int insert(UserWeiboLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    int insertSelective(UserWeiboLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    List<UserWeiboLike> selectByExample(UserWeiboLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    UserWeiboLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    int updateByExampleSelective(@Param("record") UserWeiboLike record, @Param("example") UserWeiboLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    int updateByExample(@Param("record") UserWeiboLike record, @Param("example") UserWeiboLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    int updateByPrimaryKeySelective(UserWeiboLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_weibo_like
     *
     * @mbg.generated Tue Apr 30 21:08:34 EDT 2019
     */
    int updateByPrimaryKey(UserWeiboLike record);
}