package com.example.weibohuati.mapper;

import com.example.weibohuati.model.UserTopicRead;

public interface UserTopicReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_read
     *
     * @mbg.generated Sat May 04 10:43:25 EDT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_read
     *
     * @mbg.generated Sat May 04 10:43:25 EDT 2019
     */
    int insert(UserTopicRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_read
     *
     * @mbg.generated Sat May 04 10:43:25 EDT 2019
     */
    int insertSelective(UserTopicRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_read
     *
     * @mbg.generated Sat May 04 10:43:25 EDT 2019
     */
    UserTopicRead selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_read
     *
     * @mbg.generated Sat May 04 10:43:25 EDT 2019
     */
    int updateByPrimaryKeySelective(UserTopicRead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_read
     *
     * @mbg.generated Sat May 04 10:43:25 EDT 2019
     */
    int updateByPrimaryKey(UserTopicRead record);
}