package com.example.weibohuati.mapper;

import com.example.weibohuati.model.UserTopicFollow;

public interface UserTopicFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_follow
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_follow
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    int insert(UserTopicFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_follow
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    int insertSelective(UserTopicFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_follow
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    UserTopicFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_follow
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    int updateByPrimaryKeySelective(UserTopicFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_follow
     *
     * @mbg.generated Sat May 04 10:43:04 EDT 2019
     */
    int updateByPrimaryKey(UserTopicFollow record);
}