package com.example.weibohuati.mapper;

import com.example.weibohuati.model.Weibo;
import com.example.weibohuati.model.WeiboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeiboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    long countByExample(WeiboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    int deleteByExample(WeiboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    int insert(Weibo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    int insertSelective(Weibo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    List<Weibo> selectByExample(WeiboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    Weibo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    int updateByExampleSelective(@Param("record") Weibo record, @Param("example") WeiboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    int updateByExample(@Param("record") Weibo record, @Param("example") WeiboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    int updateByPrimaryKeySelective(Weibo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibo
     *
     * @mbg.generated Sun Apr 14 16:34:35 EDT 2019
     */
    int updateByPrimaryKey(Weibo record);

    List<Weibo> listWeibo();

    int increaseLikeCount(Integer id);
}