package com.example.weibohuati.model;

import java.io.Serializable;

public class Topic implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.description
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.read_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    private Integer read_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.follow_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    private Integer follow_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.discuss_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    private Integer discuss_count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.description
     *
     * @return the value of topic.description
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.description
     *
     * @param description the value for topic.description
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.read_count
     *
     * @return the value of topic.read_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public Integer getRead_count() {
        return read_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.read_count
     *
     * @param read_count the value for topic.read_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public void setRead_count(Integer read_count) {
        this.read_count = read_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.follow_count
     *
     * @return the value of topic.follow_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public Integer getFollow_count() {
        return follow_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.follow_count
     *
     * @param follow_count the value for topic.follow_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public void setFollow_count(Integer follow_count) {
        this.follow_count = follow_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.discuss_count
     *
     * @return the value of topic.discuss_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public Integer getDiscuss_count() {
        return discuss_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.discuss_count
     *
     * @param discuss_count the value for topic.discuss_count
     *
     * @mbg.generated Sat May 04 10:32:22 EDT 2019
     */
    public void setDiscuss_count(Integer discuss_count) {
        this.discuss_count = discuss_count;
    }
}